## Python summary part 3

## Error handling

- syntax error
- runtime error
- logical errors

syntax error

In [4]:
prin("linear regression blabla") 

NameError: name 'prin' is not defined

In [3]:
print("linear regression blabla")

linear regression blabla


runtime error

In [5]:
numbers = list(range(5))
numbers

[0, 1, 2, 3, 4]

In [7]:
numbers[10]

IndexError: list index out of range

logical error

In [11]:
import numpy as np

radius = 5
area_circle = np.pi*radius

# error: area = pi*radius**2
area_circle

15.707963267948966

try-except

In [12]:
age = float(input("Give me your age"))
age

53.0

In [14]:
try:
    age = float(input("Give me your age"))
except ValueError as err:
    print(err)

age

could not convert string to float: '42w'


53.0

In [19]:
while True:
    try:
        age = float(input("Give me your age"))
        if not 0 <= age <= 125:
            raise ValueError("Year must be between 0 and 125")
        print(f"You are {age} years old")
        break
    except ValueError as err:
        print(err)

You are 122.0.0f years old


## Functions

In [22]:
def squarer(x): # x is input parameter
    return x**2 # return statement

squarer(4) # 3 is an argument

16

In [23]:
squares = [squarer(i) for i in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

default value

In [24]:
def draw_ascii(number_rows = 5): 
    for i in range(1, number_rows +1):
        print(i*"x " + (number_rows - i) * "o ")
        
draw_ascii()

x o o o o 
x x o o o 
x x x o o 
x x x x o 
x x x x x 


In [27]:
draw_ascii(7)

x o o o o o o 
x x o o o o o 
x x x o o o o 
x x x x o o o 
x x x x x o o 
x x x x x x o 
x x x x x x x 


In [28]:
draw_ascii(number_rows=3)

x o o 
x x o 
x x x 


arbitrary arguments, *args

In [31]:
def mean_(*args):
    sum_ = 0
    print(args) # args is a tuple
    # for arg in args:

mean_(1,2,34)

(1, 2, 34)


In [33]:
def mean_(*args):
    sum_ = 0
    for arg in args:
        sum_ += arg
    return sum_/len(args)

mean_(1,2,34)

12.333333333333334

In [34]:
mean_(1,2,3)

2.0

keyword arguments,**kwargs

In [37]:
import numpy as np

def simulate_dices(throws=1, dices=2):
    print(np.random.randint(1,7, size = (throws, dices)))

# default arguments
simulate_dices()

[[2 2]]


In [39]:
simulate_dices(1,4)

[[3 2 4 4]]


In [41]:
simulate_dices(3,4)

[[4 6 1 3]
 [2 3 5 4]
 [1 3 6 5]]


In [42]:
simulate_dices(throws=5)

[[4 6]
 [5 1]
 [4 2]
 [2 2]
 [2 5]]


In [43]:
simulate_dices(dices=3)

[[4 1 3]]


In [44]:
simulate_dices(dices=5, throws=3)

[[1 6 1 3 3]
 [6 5 5 2 6]
 [6 3 1 6 2]]


In [45]:
options = {"dices":3,"throws":3}

simulate_dices(**options)

[[5 2 3]
 [2 3 5]
 [1 2 2]]


In [46]:
option_list = [1,5]

In [47]:
simulate_dices(*option_list)

[[1 2 4 1 1]]


lambda functions

In [48]:
f = lambda x: x**3
f(3)

27

In [51]:
students = [("Charlie", 42), ("David", 25), ("Bob", 24)]
students

[('Charlie', 42), ('David', 25), ('Bob', 24)]

In [50]:
sorted(students)

[('Bob', 24), ('Charlie', 42), ('David', 25)]

In [53]:
sorted(students, key = lambda student: student[1], reverse=True)

[('Charlie', 42), ('David', 25), ('Bob', 24)]